version: '3.8'

services:
  web:
    env_file: database.conf
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    env_file: database.conf
    ports: 
      - "5432:5432"
  