version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    expose: 
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres
    env_file: database.conf
    expose:
      - 5432
    ports: 
      - 5432:5432
  